# Generated by Django 6.0.6 on 2026-07-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machinery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='machinery/')),
                ('description', models.TextField()),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
