# Generated by Django 6.0.6 on 2026-07-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_testimonial_companyprofile_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
